name: analyze_arXiv_papers
dependencies:
  - python=3.7
  - ipython
  - jupyterlab
  - nbgitpuller
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - spacy
  - pip:
    - arxiv
    - git+https://github.com/Miguel-ASM/TeX-counter.git
